version: "2"

volumes:
  jenkins-data:
    external: false

services:
  jenkins:
    image: jenkinsci/blueocean:1.6.1
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}:/home
