version: "2"

volumes:
  jenkins-data:
    external: false

services:
  blueocean:
    image: jenkinsci/blueocean:1.6.1
    restart: always
    ports:
      - "8080:8080"
    environment:
      - http.proxyHost=${JAVA_HTTP_PROXY_HOST}
      - http.proxyPort=${JAVA_HTTP_PROXY_PORT}
      - https.proxyHost=${JAVA_HTTPS_PROXY_HOST}
      - https.proxyPort=${JAVA_HTTPS_PROXY_PORT}
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}:/home
