version: "3.0"

volumes:
  data:
    driver: local

services:
  git-cache-http-server:
    restart: always
    build:
      context: .
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    ports:
      - "8080:8080"
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
    volumes:
      - data:/data
