version: "3.0"

volumes:
  data:
    driver: local

services:
  git-cache-http-server:
    build:
      context: .
      # args:
      #   - http_proxy=${http_proxy}
      #   - https_proxy=${https_proxy}
    environment:
      - NODE_ENV=production
      # - http_proxy=${http_proxy}
      # - https_proxy=${https_proxy}
      # - no_proxy=${no_proxy}
    ports:
      - "9080:8080"
    restart: always
    volumes:
      - data:/var/cache/git
