version: "3"

volumes:
  dnsmasq:
    external: false
  pihole:
    external: false

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Asia/Shanghai'
      WEBPASSWORD: 'admin'
    volumes:
      - 'pihole:/etc/pihole/'
      - 'dnsmasq:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 114.114.114.114
      - 1.1.1.1
    restart: unless-stopped
