version: "2"

volumes:
  gitea:
    external: false

services:
  gitea:
    image: gitea/gitea:1.7.3
    restart: always
    environment:
      - APP_NAME=Gitea Host
      - RUN_MODE=prod
      - DOMAIN=${DOMAIN}
      - ROOT_URL=http://${DOMAIN}:13000
      - SSH_PORT=10022
      - DB_TYPE=sqlite3
      - DISABLE_REGISTRATION=true
      - REQUIRE_SIGNIN_VIEW=true
    ports:
      - "13000:3000"
      - "10022:22"
    volumes:
      - gitea:/data
