version: "2"

volumes:
  gitea-data:
    driver: local
  gitea-config:
    driver: local
  mariadb:
    driver: local

services:
  gitea:
    depends_on:
      - db
    environment:
      - APP_NAME="My Gitea Server"
      - RUN_MODE=prod
      - RUN_USER=git
      - GITEA__actions__ENABLED=false
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__database__USER=gitea
      - GITEA__mailer__ENABLED=false
      - GITEA__repository__DEFAULT_BRANCH=master
      - GITEA__repository__DEFAULT_PRIVATE=true
      - GITEA__repository__DISABLE_HTTP_GIT=true
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__ROOT_URL=http://192.168.39.117:3000/
      - GITEA__server__SSH_DOMAIN=192.168.39.117
      - GITEA__server__SSH_PORT=2222
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__REQUIRE_SIGNIN_VIEW=true
      - GITEA__time__DEFAULT_UI_LOCATION=Asia/Shanghai
    image: docker.io/gitea/gitea:1.21.1-rootless
    ports:
      - '3000:3000'
      - '2222:2222'
    restart: always
    volumes:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  db:
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    image: docker.io/library/mariadb:11.2.2
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
