---
version: "3"

services: 
  kcptun:
    command: ["/bin/server", "-c", "/etc/kcptun.json"]
    image: xtaci/kcptun:v20200226
    ports:
      - ${KCPTUN_PORT}:29900/udp
    restart: always
    volumes:
      - "./kcptun-server.json:/etc/kcptun.json"

  shadowsocks:
    image: shadowsocks/shadowsocks-libev:v3.3.4
    ports:
      - "${SHADOWSOCK_PORT}:8388/tcp"
      - "${SHADOWSOCK_PORT}:8388/udp"
    environment:
      - ARGS=--fast-open --reuse-port --no-delay
      - METHOD=aes-256-gcm
      - PASSWORD=${SHADOWSOCK_PASSWORD}
    restart: always
