version: '3'

volumes:
  db:
    external: false

services:
  db:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_USER: 'test'
    image: mariadb:10.6.4
    ports:
      - "3306:3306"
      - "33060:33060"
    # restart: always
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5.1.1
    environment:
      MYSQL_ROOT_PASSWORD: ''
      PMA_HOST: 'db'
    ports:
      - "8080:80"
