version: "3"

services: 
  shadowsocks:
    image: shadowsocks/shadowsocks-libev:v3.3.4
    ports:
      - "${SHADOWSOCK_PORT}:8388"
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=${SHADOWSOCK_PASSWORD}
    restart: always
