version: "3"

services: 
  shadowsocks:
    image: shadowsocks/shadowsocks-libev:${SHADOWSOCKS_LIBEV_VERSION}
    ports:
      - "${SHADOWSOCK_PORT}:8388/tcp"
      - "${SHADOWSOCK_PORT}:8388/udp"
    environment:
      - ARGS=--fast-open --reuse-port --no-delay
      - METHOD=aes-256-gcm
      - PASSWORD=${SHADOWSOCK_PASSWORD}
    restart: always
