version: '2'

services:
  gitea:
    depends_on:
      - mariadb
    environment:
# default
      - APP_NAME=Gitea
      - RUN_MODE=prod
      - RUN_USER=git
# repository
      - DEFAULT_PRIVATE=private
# server
      - DOMAIN=${DOMAIN}
      - ROOT_URL=http://${DOMAIN}:13000
      - SSH_PORT=22
# database
      - CHARSET=utf8mb4
      - DB_HOST=mariadb
      - DB_NAME=gitea
      - DB_PASSWD=gitea
      - DB_TYPE=mysql
      - DB_USER=gitea
# service
      - DISABLE_REGISTRATION=true
      - REQUIRE_SIGNIN_VIEW=true
# mailer
      - ENABLED=false
    image: gitea/gitea:${GITEA_VERSION}
    ports:
      - '10022:22/tcp'
      - '13000:3000/tcp'
    restart: always
    volumes:
      - gitea:/data

  mariadb:
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    image: mariadb:10.4.12
    restart: always
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  gitea:
    external: false
  mariadb:
    driver: local
