services:
  gitea:
    depends_on:
      - mariadb
    environment:
      - APP_NAME=Gitea Host
      - DB_HOST=mariadb
      - DB_NAME=gitea
      - DB_PASSWD=gitea
      - DB_TYPE=mysql
      - DB_USER=gitea
      - DEFAULT_PRIVATE=private
      - DISABLE_REGISTRATION=true
      - DOMAIN=${DOMAIN}
      - REQUIRE_SIGNIN_VIEW=true
      - ROOT_URL=http://${DOMAIN}:13000
      - RUN_MODE=prod
      - SSH_PORT=10022
    image: gitea/gitea:${GITEA_VERSION}
    ports:
      - '10022:22'
      - '13000:3000'
    restart: always
    volumes:
      - gitea:/data
  mariadb:
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    image: mariadb:10.4.12
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
version: '2'
volumes:
  gitea:
    external: false
  mariadb:
    driver: local
