version: '2'

services:
  gitea:
    depends_on:
      - mariadb
    environment:
      - USER_UID=1000
      - USER_GID=1000
# default
      - APP_NAME=Gitea
      - RUN_MODE=prod
      - RUN_USER=git
# repository
      - DEFAULT_PRIVATE=private
# server
      - DOMAIN=${DOMAIN}
      - ROOT_URL=https://${DOMAIN}
      - SSH_PORT=${SSH_PORT}
# database
      - CHARSET=utf8mb4
      - DB_HOST=mariadb
      - DB_NAME=gitea
      - DB_PASSWD=gitea
      - DB_TYPE=mysql
      - DB_USER=gitea
      - LOG_SQL=false
# service
      - DISABLE_REGISTRATION=true
      - REQUIRE_SIGNIN_VIEW=true
# mailer
      - ENABLED=false
    image: gitea/gitea:${GITEA_VERSION}
    ports:
      - '${SSH_PORT}:${SSH_PORT}/tcp'
      - '127.0.0.1:${HTTP_PORT}:${HTTP_PORT}/tcp'
    restart: always
    volumes:
      - gitea:/data

  mariadb:
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    image: mariadb:10.4.12
    restart: always
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  gitea:
    external: false
  mariadb:
    driver: local
