version: '3.0'

volumes:
  go:
    driver: local

services:
  goproxy:
    command: ["-cacheDir", "/go", "-proxy", "https://goproxy.io"]
    image: goproxy/goproxy
    ports: 
      - 8081:8081
    restart: always
    volumes:
      - go:/go
