version: '3.1'

services:

  mongo:
    image: docker.io/library/mongo:4.4.4-bionic
    # restart: always
    ports:
      - 3000:3000
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: docker.io/library/mongo-express:0.54
    # restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
